[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "documentation_basic"
classifiers = ["Private :: Do Not Upload"]
version = "0"
dependencies = []


[project.optional-dependencies]
docs = [
    "jupyter-book",
    "jupytext",
]
