[build-system]
requires = ["setuptools>=61.2"]
build-backend = "setuptools.build_meta"

[project]
name = "documentation-basic"
version = "0.1.0"
dependencies = []


[project.optional-dependencies]
docs = [
    "jupyter-book",
    "jupytext",
]
