name: Build documentation and upload artifact

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    branches: main

env:
  # Directory that will be published on github pages
  PUBLISH_DIR: ./_build/html

jobs:

  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python3 -m pip install .

      - name: Build docs
        run: jupyter book build .

      - name: Use Node v18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Build slides
        run: |
          npx @marp-team/marp-cli docs/intro.md --html -o ${{ env.PUBLISH_DIR }}/intro-slides.html
          npx @marp-team/marp-cli docs/repo.md --html -o ${{ env.PUBLISH_DIR }}/repo-slides.html
          npx @marp-team/marp-cli docs/environments.md --html -o ${{ env.PUBLISH_DIR }}/environments-slides.html
          npx @marp-team/marp-cli docs/documentation.md --html -o ${{ env.PUBLISH_DIR }}/documentation-slides.html
          npx @marp-team/marp-cli docs/testing.md --html -o ${{ env.PUBLISH_DIR }}/testing-slides.html
          npx @marp-team/marp-cli docs/paper.md --html -o ${{ env.PUBLISH_DIR }}/paper-slides.html
          npx @marp-team/marp-cli docs/distribution.md --html -o ${{ env.PUBLISH_DIR }}/distribution-slides.html


      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: ${{ env.PUBLISH_DIR }}
          if-no-files-found: error
          name: documentation
